export enum OrderStatusEnum {
  START_TRANSACTION = "start_transaction",
  PENDING_USER_PAYMENT = "pending_user_payment",
  PENDING_TRANSACTION_SUCCESS_STATUS = "pending_transaction_success_status",
  PENDING_ADMIN_APPROVAL = "pending_admin_approval",
  EXECUTION_SYSTEM_ORDER_TO_DEFAULT_TOKEN = "execution_system_order_to_default_token",
  PENDING_TO_CONFIRM_EXECUTION_SYSTEM_ORDER_TO_DEFAULT_TOKEN = "pending_to_confirm_execution_system_order_to_default_token",
  EXECUTION_SYSTEM_ORDER_TO_RECEIVING_TOKEN = "execution_system_order_to_receiving_token",
  PENDING_TO_CONFIRM_EXECUTION_SYSTEM_ORDER_TO_RECEIVING_TOKEN = "pending_to_confirm_execution_system_order_to_receiving_token",
  EXECUTION_SYSTEM_TRANSACTION = "execution_system_transaction",
  PENDING_TO_CONFIRM_EXECUTION_SYSTEM_TRANSACTION = "pending_to_confirm_execution_system_transaction",
  COMPLETED = "completed",
  CANCEL = "cancel",
  EXPIRED = "expired",
}
